try fix

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -38,25 +38,34 @@ jobs:
           KUBECONFIG=./configs/cluster2.yaml minikube start -p test-cluster-2 &
           wait
 
-      - name: Run kube-switcher - switch cluster context
+      - name: Switch context to test-cluster-1
         run: ./kube-switcher context test-cluster-1
 
-      - name: List Kubernetes Nodes
-        run: kubectl get nodes | grep "test-cluster-1"
-
-      - name: Run kube-switcher - switch cluster namespace
+      - name: Validate the cluster has switched to test-cluster-1 by listing nodes
         run: |
-          kubectl get pods | grep "No resources found in default namespace."
-          ./kube-switcher namespace kube-system
-          kubectl get pods | grep "apiserver"
+          kubectl get nodes | grep "test-cluster-1" || { echo "Error: test-cluster-1 not found in node list!" >&2; exit 1; }
 
-      - name: Run kube-switcher - switch context shorthand
+      - name: Check that no pods are found in the default namespace
         run: |
-          ./kube-switcher ns default
-          kubectl get pods | grep "No resources found in default namespace."
+          kubectl get pods --namespace=default 2>&1 | grep "No resources found" || { echo "Error: Pods found in default namespace!" >&2; exit 1; }
 
-      - name: Run kube-switcher - switch cluster shorthand
-        run: ./kube-switcher ctx test-cluster-2
+      - name: Switch to the kube-system namespace
+        run: ./kube-switcher namespace kube-system
 
-      - name: List Kubernetes Nodes
-        run: kubectl get nodes | grep "test-cluster-2"
+      - name: Validate that kube-system namespace is selected and kube-apiserver is running
+        run: |
+          kubectl get pods --namespace=kube-system | grep "kube-apiserver" || { echo "Error: kube-apiserver not found in kube-system!" >&2; exit 1; }
+
+      - name: Switch back to the default namespace
+        run: ./kube-switcher namespace default
+
+      - name: Check that no pods are found again in the default namespace
+        run: |
+          kubectl get pods --namespace=default 2>&1 | grep "No resources found" || { echo "Error: Pods found in default namespace!" >&2; exit 1; }
+
+      - name: Switch context to test-cluster-2
+        run: ./kube-switcher context test-cluster-2
+
+      - name: Validate the cluster has switched to test-cluster-2 by listing nodes
+        run: |
+          kubectl get nodes | grep "test-cluster-2" || { echo "Error: test-cluster-2 not found in node list!" >&2; exit 1; }
